#!/bin/env bash
set -Eeuo pipefail
shopt -s nullglob globstar
unset LD_PRELOAD
## Declare getprops
getpropcommandsa=("getprop gsm.sim.operator.iso-country" "getprop net.bt.name" "getprop persist.sys.locale" "getprop ro.build.target_country" "getprop ro.build.version.release" "getprop ro.build.version.sdk" "getprop ro.product.device" "getprop ro.product.first_api_level" "getprop ro.product.locale" "getprop ro.product.manufacturer" "getprop ro.product.model")
for i in "${!getpropcommandsa[@]}"; do
	getpropcommandst+="\\e[1;32m[${getpropcommandsa[$i]}]: [`${getpropcommandsa[$i]}`]\\e[0;32m\\n"
done
printf  "$getpropcommandst"
#	## Used to generate signals.
#  	((1/0)) # 1
# 	echo hello | grep "asdf" # 1
# 	format c: #127
#  	. foo
#  	. 35e493e
# 	 (false; echo one) | cat; echo two # 1 & 201
# 	cat
##
#		apt update && apt -o APT::Keep-Downloaded-Packages="true" upgrade -y
#		apt -o APT::Keep-Downloaded-Packages="true" install "$aptin" -y
echo user.language
getprop user.language
echo user.region
getprop user.region
echo persist.sys.locale
getprop persist.sys.locale
echo persist.sys.language
getprop persist.sys.language
echo ro.product.locale
getprop ro.product.locale
echo ro.product.locale.language
getprop ro.product.locale.language
echo ro.product.locale.region
getprop ro.product.locale.region
echo ro.build.target_country
getprop ro.build.target_country
user.language
 [pt] 
user.region
 [BR] 
persist.sys.locale
fr-CA
persist.sys.language
 [pt] 
ro.product.locale
en-US
ro.product.locale.language
 [en] 
ro.product.locale.region
 [GB]
ro.build.target_country
US


[persist.sys.language]: [pt] 
[ro.product.locale.language]: [en] 
[ro.product.locale.region]: [GB]
[user.language]: [pt] 
[user.region]: [BR] 

[09:37 sdcard ]$ awk '{print $0}' file > tmp && mv tmp file                               awk: file: No such file or directory                                                      [09:40 sdcard ]$ awk '/en/ && /GB/ && /UTF/ { print substr($1,2);}' locale.gen
en_GB.UTF-8
# 	# Checks and sets dm if download manager is present. 
# 	# IMPORTANT NOTE: CURRENTLY ONLY curl AND wget ARE THOROUGHLY TESTED.   All the download managers are NOT yet fully implemented.    
_DEPENDDM_() {
	ADM=([aria2]=aria2c [axel]=axel [curl]=curl [lftp]=lftpget [wget]=wget) # Reference http://www.artificialworlds.net/blog/2012/10/17/bash-associative-array-examples/
# 	# ADM[pkg]=cmd # Ordinary assignment adds another single element to the array.
	for cmd in "${!ADM[@]}"; do # Enumerates download manager commands from all the available Termux https capable download manager packages.  
		if [[ -x "$PREFIX"/bin/$cmd ]] ; then
# 			PDM=([${ADM[$cmd]}]=$cmd) # Create reverse associative array if cmd is present. 
#		#	PDM[${ADM[$cmd]}]=$cmd # Builds associative array if cmds are present. 
			PDM[$cmd]="${ADM[$cmd]}" # Create associative array if cmd is present. 
			break
		fi
	done
# 		PDM=([wget]=wget) # Create associative array if cmd is not present. 
	echo here
	exit
	PDM[$cmd]="${ADM[$cmd]}" # Create associative array if cmd is present. 
	dm="${!ADM[@]}"	# Sets download manager.
	declare -p "${!ADM[@]}" ||:
	declare -p "${ADM[@]}" ||:
	printf "%s" "${!ADM[@]}" ||:
	printf "\n" 
	printf "%s" "${ADM[@]}" ||:
#	# read -p "Press enter to continue" # https://unix.stackexchange.com/questions/293940/bash-how-can-i-make-press-any-key-to-continue
# 	# read -n 1 -s -r -p "Press any key to continue" # https://unix.stackexchange.com/questions/293940/bash-how-can-i-make-press-any-key-to-continue
# 	# exit
	if [[ "$dm" = "" ]] ; then
		echo
		echo "Found no https capable download managers present on device: Continuing…"
	fi
	echo here
	exit

